TRANSLATIONS = {
    "en": {
        "app_title": "Global Accounting",
        "dashboard": "Dashboard",
        "invoices": "Invoices",
        "inventory": "Inventory",
        "payroll": "Payroll",
        "reports": "Reports",
        "settings": "Settings",
        "company_name": "Company name",
        "country": "Country",
        "currency": "Currency",
        "tax_rate": "Tax rate",
        "language": "Language",
        "save": "Save",
        "invoice_number": "Invoice Number",
        "customer_name": "Customer Name",
        "product_name": "Product Name",
        "quantity": "Quantity",
        "unit_price": "Unit Price",
        "add_item": "Add Item",
        "create_invoice": "Create Invoice",
        "product_code": "Product Code",
        "product_category": "Category",
        "unit": "Unit",
        "cost_price": "Cost Price",
        "selling_price": "Selling Price",
        "stock_quantity": "Stock Quantity",
        "min_stock": "Min Stock",
        "add_product": "Add Product",
        "employee_name": "Employee Name",
        "position": "Position",
        "salary": "Salary",
        "bonus": "Bonus",
        "deductions": "Deductions",
        "bank_account": "Bank Account",
        "period": "Period",
        "add_employee": "Add Employee",
        "generate_payroll": "Generate Payroll",
        "total_products": "Total Products",
        "inventory_value": "Inventory Qty",
        "total_invoices": "Total Invoices",
        "sales_total": "Sales Total",
        "employees_count": "Employees",
    },
    "ar": {
        "app_title": "جلوبال للمحاسبة",
        "dashboard": "لوحة التحكم",
        "invoices": "الفواتير",
        "inventory": "المخزون",
        "payroll": "الرواتب",
        "reports": "التقارير",
        "settings": "الإعدادات",
        "company_name": "اسم الشركة",
        "country": "الدولة",
        "currency": "العملة",
        "tax_rate": "نسبة الضريبة",
        "language": "اللغة",
        "save": "حفظ",
        "invoice_number": "رقم الفاتورة",
        "customer_name": "اسم العميل",
        "product_name": "اسم المنتج",
        "quantity": "الكمية",
        "unit_price": "سعر الوحدة",
        "add_item": "إضافة عنصر",
        "create_invoice": "إنشاء فاتورة",
        "product_code": "رمز المنتج",
        "product_category": "الفئة",
        "unit": "الوحدة",
        "cost_price": "سعر التكلفة",
        "selling_price": "سعر البيع",
        "stock_quantity": "الكمية الحالية",
        "min_stock": "الحد الأدنى",
        "add_product": "إضافة منتج",
        "employee_name": "اسم الموظف",
        "position": "الوظيفة",
        "salary": "الراتب",
        "bonus": "العلاوة",
        "deductions": "الخصومات",
        "bank_account": "الحساب البنكي",
        "period": "الفترة",
        "add_employee": "إضافة موظف",
        "generate_payroll": "إنشاء راتب",
        "total_products": "إجمالي المنتجات",
        "inventory_value": "إجمالي المخزون",
        "total_invoices": "إجمالي الفواتير",
        "sales_total": "إجمالي المبيعات",
        "employees_count": "عدد الموظفين",
    },
}


class Translator:
    def __init__(self, language="en"):
        self.language = language

    def t(self, key: str) -> str:
        return TRANSLATIONS.get(self.language, TRANSLATIONS["en"]).get(key, key)
