import sqlite3
from datetime import datetime

from config.config import DB_PATH
from database.db import get_connection


def get_company():
    conn = get_connection()
    row = conn.execute("SELECT * FROM companies ORDER BY id DESC LIMIT 1").fetchone()
    conn.close()
    return dict(row) if row else {}


def save_company(name, country, currency, tax_rate, language):
    conn = get_connection()
    conn.execute(
        "UPDATE companies SET name = ?, country = ?, currency = ?, tax_rate = ?, language = ? WHERE id = 1",
        (name, country, currency, tax_rate, language),
    )
    conn.commit()
    conn.close()


def add_product(code, name, category, unit, cost_price, selling_price, stock_quantity, min_stock):
    conn = get_connection()
    conn.execute(
        "INSERT INTO products (code, name, category, unit, cost_price, selling_price, stock_quantity, min_stock) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
        (code, name, category, unit, cost_price, selling_price, stock_quantity, min_stock),
    )
    conn.commit()
    conn.close()


def get_products():
    conn = get_connection()
    rows = conn.execute("SELECT * FROM products ORDER BY id DESC").fetchall()
    conn.close()
    return [dict(row) for row in rows]


def add_customer(name, phone, email, address):
    conn = get_connection()
    conn.execute(
        "INSERT INTO customers (name, phone, email, address) VALUES (?, ?, ?, ?)",
        (name, phone, email, address),
    )
    conn.commit()
    conn.close()


def get_customers():
    conn = get_connection()
    rows = conn.execute("SELECT * FROM customers ORDER BY id DESC").fetchall()
    conn.close()
    return [dict(row) for row in rows]


def add_employee(name, position, salary, bonus, deductions, bank_account):
    conn = get_connection()
    conn.execute(
        "INSERT INTO employees (name, position, salary, bonus, deductions, bank_account) VALUES (?, ?, ?, ?, ?, ?)",
        (name, position, salary, bonus, deductions, bank_account),
    )
    conn.commit()
    conn.close()


def get_employees():
    conn = get_connection()
    rows = conn.execute("SELECT * FROM employees ORDER BY id DESC").fetchall()
    conn.close()
    return [dict(row) for row in rows]


def create_invoice(invoice_number, customer_name, items, tax_rate):
    conn = get_connection()
    subtotal = sum(item["quantity"] * item["unit_price"] for item in items)
    tax_amount = subtotal * tax_rate
    total = subtotal + tax_amount

    conn.execute(
        "INSERT INTO invoices (invoice_number, invoice_date, customer_name, invoice_type, subtotal, tax_amount, total, notes) VALUES (?, ?, ?, 'sale', ?, ?, ?, 'Generated by Global')",
        (invoice_number, datetime.now().strftime("%Y-%m-%d"), customer_name, subtotal, tax_amount, total),
    )
    invoice_id = conn.execute("SELECT last_insert_rowid()").fetchone()[0]

    for item in items:
        product_name = item["name"]
        quantity = float(item["quantity"])
        unit_price = float(item["unit_price"])
        total_line = quantity * unit_price
        conn.execute(
            "INSERT INTO invoice_items (invoice_id, product_name, quantity, unit_price, total) VALUES (?, ?, ?, ?, ?)",
            (invoice_id, product_name, quantity, unit_price, total_line),
        )

        existing = conn.execute("SELECT id, stock_quantity FROM products WHERE name = ? LIMIT 1", (product_name,)).fetchone()
        if existing:
            new_stock = float(existing["stock_quantity"]) - quantity
            conn.execute("UPDATE products SET stock_quantity = ? WHERE id = ?", (new_stock, existing["id"]))

    conn.commit()
    conn.close()
    return invoice_id


def get_invoices():
    conn = get_connection()
    rows = conn.execute("SELECT * FROM invoices ORDER BY id DESC").fetchall()
    conn.close()
    return [dict(row) for row in rows]


def create_payroll(employee_id, period, gross_salary, bonus, deductions):
    net_salary = gross_salary + bonus - deductions
    conn = get_connection()
    conn.execute(
        "INSERT INTO payroll (employee_id, period, gross_salary, bonus, deductions, net_salary) VALUES (?, ?, ?, ?, ?, ?)",
        (employee_id, period, gross_salary, bonus, deductions, net_salary),
    )
    conn.commit()
    conn.close()


def get_payroll():
    conn = get_connection()
    rows = conn.execute(
        "SELECT p.*, e.name AS employee_name FROM payroll p JOIN employees e ON e.id = p.employee_id ORDER BY p.id DESC"
    ).fetchall()
    conn.close()
    return [dict(row) for row in rows]


def get_dashboard_summary():
    conn = get_connection()
    products = conn.execute("SELECT COUNT(*) AS count, COALESCE(SUM(stock_quantity), 0) AS total_stock FROM products").fetchone()
    invoices = conn.execute("SELECT COUNT(*) AS count, COALESCE(SUM(total), 0) AS sales FROM invoices").fetchone()
    employees = conn.execute("SELECT COUNT(*) AS count FROM employees").fetchone()
    conn.close()
    return {
        "products": products["count"],
        "total_stock": products["total_stock"],
        "invoices": invoices["count"],
        "sales": invoices["sales"],
        "employees": employees["count"],
    }
