# model definitions for clarity and future expansion

TABLES = {
    "companies": [
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "name TEXT NOT NULL",
        "country TEXT",
        "currency TEXT DEFAULT 'USD'",
        "tax_rate REAL DEFAULT 0.15",
        "language TEXT DEFAULT 'en'",
    ],
    "products": [
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "code TEXT UNIQUE",
        "name TEXT NOT NULL",
        "category TEXT",
        "unit TEXT",
        "cost_price REAL DEFAULT 0",
        "selling_price REAL DEFAULT 0",
        "stock_quantity REAL DEFAULT 0",
        "min_stock REAL DEFAULT 0",
    ],
    "customers": [
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "name TEXT NOT NULL",
        "phone TEXT",
        "email TEXT",
        "address TEXT",
    ],
    "suppliers": [
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "name TEXT NOT NULL",
        "phone TEXT",
        "email TEXT",
        "address TEXT",
    ],
    "invoices": [
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "invoice_number TEXT UNIQUE",
        "invoice_date TEXT NOT NULL",
        "customer_id INTEGER",
        "customer_name TEXT",
        "invoice_type TEXT DEFAULT 'sale'",
        "subtotal REAL DEFAULT 0",
        "tax_amount REAL DEFAULT 0",
        "total REAL DEFAULT 0",
        "notes TEXT",
    ],
    "invoice_items": [
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "invoice_id INTEGER NOT NULL",
        "product_id INTEGER",
        "product_name TEXT NOT NULL",
        "quantity REAL NOT NULL",
        "unit_price REAL NOT NULL",
        "total REAL NOT NULL",
    ],
    "employees": [
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "name TEXT NOT NULL",
        "position TEXT",
        "salary REAL DEFAULT 0",
        "bonus REAL DEFAULT 0",
        "deductions REAL DEFAULT 0",
        "bank_account TEXT",
    ],
    "payroll": [
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "employee_id INTEGER NOT NULL",
        "period TEXT NOT NULL",
        "gross_salary REAL DEFAULT 0",
        "bonus REAL DEFAULT 0",
        "deductions REAL DEFAULT 0",
        "net_salary REAL DEFAULT 0",
    ],
}
