import sqlite3
from datetime import datetime

from database.db import get_connection


class AccountingService:
    def __init__(self):
        self.conn = get_connection()

    def close(self):
        self.conn.close()

    def get_company(self):
        row = self.conn.execute("SELECT * FROM companies ORDER BY id DESC LIMIT 1").fetchone()
        return dict(row) if row else {}

    def save_company(self, name, country, currency, tax_rate, language):
        self.conn.execute(
            "UPDATE companies SET name = ?, country = ?, currency = ?, tax_rate = ?, language = ? WHERE id = 1",
            (name, country, currency, tax_rate, language),
        )
        self.conn.commit()

    def list_products(self):
        return [dict(r) for r in self.conn.execute("SELECT * FROM products ORDER BY id DESC").fetchall()]

    def add_product(self, code, name, category, unit, cost_price, selling_price, stock_quantity, min_stock):
        self.conn.execute(
            "INSERT INTO products (code, name, category, unit, cost_price, selling_price, stock_quantity, min_stock) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (code, name, category, unit, cost_price, selling_price, stock_quantity, min_stock),
        )
        self.conn.commit()

    def list_customers(self):
        return [dict(r) for r in self.conn.execute("SELECT * FROM customers ORDER BY id DESC").fetchall()]

    def add_customer(self, name, phone, email, address):
        self.conn.execute(
            "INSERT INTO customers (name, phone, email, address) VALUES (?, ?, ?, ?)",
            (name, phone, email, address),
        )
        self.conn.commit()

    def list_employees(self):
        return [dict(r) for r in self.conn.execute("SELECT * FROM employees ORDER BY id DESC").fetchall()]

    def add_employee(self, name, position, salary, bonus, deductions, bank_account):
        self.conn.execute(
            "INSERT INTO employees (name, position, salary, bonus, deductions, bank_account) VALUES (?, ?, ?, ?, ?, ?)",
            (name, position, salary, bonus, deductions, bank_account),
        )
        self.conn.commit()

    def list_invoices(self):
        return [dict(r) for r in self.conn.execute("SELECT * FROM invoices ORDER BY id DESC").fetchall()]

    def add_invoice(self, invoice_number, customer_name, items, tax_rate):
        subtotal = sum(float(item["quantity"]) * float(item["unit_price"]) for item in items)
        tax_amount = subtotal * float(tax_rate)
        total = subtotal + tax_amount

        self.conn.execute(
            "INSERT INTO invoices (invoice_number, invoice_date, customer_name, invoice_type, subtotal, tax_amount, total, notes) VALUES (?, ?, ?, 'sale', ?, ?, ?, 'Generated by Global')",
            (invoice_number, datetime.now().strftime("%Y-%m-%d"), customer_name, subtotal, tax_amount, total),
        )
        invoice_id = self.conn.execute("SELECT last_insert_rowid()").fetchone()[0]

        for item in items:
            product_name = item["name"]
            quantity = float(item["quantity"])
            unit_price = float(item["unit_price"])
            total_line = quantity * unit_price
            self.conn.execute(
                "INSERT INTO invoice_items (invoice_id, product_name, quantity, unit_price, total) VALUES (?, ?, ?, ?, ?)",
                (invoice_id, product_name, quantity, unit_price, total_line),
            )

            existing = self.conn.execute("SELECT id, stock_quantity FROM products WHERE name = ? LIMIT 1", (product_name,)).fetchone()
            if existing:
                new_stock = float(existing["stock_quantity"]) - quantity
                self.conn.execute("UPDATE products SET stock_quantity = ? WHERE id = ?", (new_stock, existing["id"]))

        self.conn.commit()
        return invoice_id

    def list_payroll(self):
        rows = self.conn.execute(
            "SELECT p.*, e.name AS employee_name FROM payroll p JOIN employees e ON e.id = p.employee_id ORDER BY p.id DESC"
        ).fetchall()
        return [dict(r) for r in rows]

    def add_payroll(self, employee_id, period, gross_salary, bonus, deductions):
        net_salary = gross_salary + bonus - deductions
        self.conn.execute(
            "INSERT INTO payroll (employee_id, period, gross_salary, bonus, deductions, net_salary) VALUES (?, ?, ?, ?, ?, ?)",
            (employee_id, period, gross_salary, bonus, deductions, net_salary),
        )
        self.conn.commit()

    def dashboard_summary(self):
        products = self.conn.execute("SELECT COUNT(*) AS count, COALESCE(SUM(stock_quantity), 0) AS total_stock FROM products").fetchone()
        invoices = self.conn.execute("SELECT COUNT(*) AS count, COALESCE(SUM(total), 0) AS sales FROM invoices").fetchone()
        employees = self.conn.execute("SELECT COUNT(*) AS count FROM employees").fetchone()
        return {
            "products": products["count"],
            "inventory_qty": products["total_stock"],
            "invoices": invoices["count"],
            "sales_total": invoices["sales"],
            "employees": employees["count"],
        }

    def get_language(self):
        company = self.get_company()
        return company.get("language", "en")
